export enum EChatSocketAction {
  CONNECT_CHAT = '(CHAT)-CONNECT_CHAT',
  LOGIN_CHAT = '(CHAT)-LOGIN_CHAT',
  SUBSCRIBE_CHAT = '(CHAT)-SUBSCRIBE_CHAT',
  GET_CHAT_HISTORY = '(CHAT)-GET_CHAT_HISTORY',
  SEND_MSG = '(CHAT)-SEND_MSG',
  RECEIVE_MSG = '(CHAT)-RECEIVE_MSG',
  RECEIVE_CHAT_HISTORY = '(CHAT)-RECEIVE_CHAT_HISTORY',
  DISCONNECT_CHAT = '(CHAT)-DISCONNECT_CHAT'
}
