export enum ECoinflipSocketAction {
  CREATE_NEW_COINFLIPGAME = '(COINFLIP)-CREATE_NEW_COINFLIPGAME',
  CONNECT_COINFLIP = '(COINFLIP)-CONNECT_COINFLIP',
  LOGIN_COINFLIP = '(COINFLIP)-LOGIN_COINFLIP',
  SUBSCRIBE_COINFLIP = '(COINFLIP)-SUBSCRIBE_COINFLIP',
  RECEIVE_MSG = '(COINFLIP)-RECEIVE_MSG',
  DISCONNECT_COINFLIP = '(COINFLIP)-DISCONNECT_COINFLIP',
  CREATE_COINFLIP_GAME = '(COINFLIP)-CREATE_COINFLIP_GAME',
  COINFLIPGAME_ROLLED = '(COINFLIP)-COINFLIPGAME_ROLLED',
  UPDATE_WALLET = '(COINFLIP)-UPDATE_WALLET',
  COINFLIP_GAME_STATUS = '(COINFLIP)-COINFLIP_GAME_STATUS',
  RESET_GAME_STATE = '(COINFLIP)-RESET_GAME_STATE'
}
