export enum ELeaderboardSocketAction {
  SUBSCRIBE_LEADERBOARD = '(LEADERBOARD)-SUBSCRIBE_LEADERBOARD',
  CONNECT_LEADERBOARD = '(LEADERBOARD)-CONNECT_LEADERBOARD',
  GET_LEADERBOARD_HISTORY = '(LEADERBOARD)-GET_LEADERBOARD_HISTORY',
  DISCONNECT_LEADERBOARD = '(LEADERBOARD)-DISCONNECT_LEADERBOARD'
}
