export enum EUserSocketAction {
  USER_DATA = '(USER)-USER_DATA',
  INIT_USER_DATA = '(USER)-INIT_USER_DATA',
  SITE_BALANCE_UPDATE = '(USER)-SITE_BALANCE_UPDATE',
  DISCONNECT_USER = '(USER)-DISCONNECT_USER',
  SET_ADMINWALLET = '(USER)-SET_ADMINWALLET',
  REMEMBERME = '(USER)-REMEMBERME',
  SET_CREDENTIALS = '(USER)-SET_CREDENTIALS',
  REMOVE_CREDENTIALS = '(USER)-REMOVE_CREDENTIALS',
  AES_KEY = '(USER)-AES_KEY',
  NEW_WALLET = '(USER)-NEW_WALLET',
  SAVE_USER = '(USER)-SAVE_USER',
  REMOVE_USER = '(USER)-REMOVE_USER'
}
